server:
  port: ${PORT}
  error:
    include-message: always
  servlet:
    context-path: /api/v1/client

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}/${MYSQL_DB}
    username: ${MYSQL_USER}
    password: ${MYSQL_PWD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PWD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

application:
  security:
    access-jwt:
      secret: ${JWT_ACCESS_SECRET}
      time-life: 10
    refresh-jwt:
      secret: ${JWT_REFRESH_SECRET}
      time-life: 1440
  frontend:
    default-url: http://localhost:8080
  sender:
    email: ${SMTP_USERNAME}
    active: true
